### ISSUE TITLE
ShareFile: Android intent failed

### ISSUE THREAD

**Issue by jona711p** [braune-digital/nativescript-share-file#11]
I'm getting this error when I try to share a pdf file :/

"ShareFile: Android intent failed"

Any idear how to fix it?

**Comment by AquilesOliveira** [comment]
Solution: `public shareAndroid(args) {
    let intent = new android.content.Intent();
    intent.addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION);

    let uris = new java.util.ArrayList();
    uris.add(args.path);
    let builder = new android.os.StrictMode.VmPolicy.Builder();
    android.os.StrictMode.setVmPolicy(builder.build());

    intent.setAction(android.content.Intent.ACTION_SEND);
    intent.setType("application/pdf");
    intent.putExtra(
      android.content.Intent.EXTRA_STREAM,
      android.net.Uri.parse("file://" + args.path)
    );

    application.android.context.startActivity(
      android.content.Intent.createChooser(
        intent,
        args.intentTitle ? args.intentTitle : "Share With:"
      )
    );
  }`

**Comment by bufke** [comment]
I was confused when I read this ticket. From what I can tell this package no longer works. @AquilesOliveira suggests a function that replaces the need for this package entirely. The shareAndroid method worked fine for me. The untyped args variable is an object similar to what this package provides.
This import is also required  `import * as application from "tns-core-modules/application";`

**Comment by soscler** [comment]
Hey @AquilesOliveira, I can't get your solution to work with MIME Types 'image/jpg' and 'image/png'.
This is my workflow
- I saved an image to the knowFolders (documents) and I use the path to share the image with other apps.

I am sure the image is saved, as the ImageSource.saveToFile method returns true and as I see the image rendered via an Image tag.
Am I missing something here ?

**Comment by soscler** [comment]
I solved my issue by using social share https://github.com/tjvantoll/nativescript-social-share.
