### ISSUE TITLE
Sharing vCard .vcf file with the contact application

### ISSUE THREAD

**Issue by lewebsimple** [braune-digital/nativescript-share-file#2]
When I `share.open(...)` a vCard file (.vcf) on Android, it doesn't suggest using the Contacts application.
Is there a way to limit or specify application(s) in the list?

Thanks for your work!

**Comment by LeonBorlinghaus** [comment]
Currently we are opening the Android intent as "message/rfc822" type. Have a look at the Android file (https://github.com/braune-digital/nativescript-share-file/blob/master/src/share-file.android.ts) and try  to edit the intent type to the one you need.

You can find out more about the Android intents here 
https://developer.android.com/reference/android/content/Intent.html
