### ISSUE TITLE
Plugin for javascript?

### ISSUE THREAD

**Issue by prolog8** [braune-digital/nativescript-share-file#3]
Hi,

May I use this plugin with JavaScript (not Typescript) ?

Because I got an error message: "TypeError: ShareFile is not a constructor ..."

Best Regards,
Willow

**Comment by pasquiermichael** [comment]
Hi,
A bit late, but you can definitely use this with javascript, just don't forget to put .ShareFile in your require.
I don't have the exact line but it should look like this 
`let shareFilePlugin = require("nativescript-share-file").ShareFile;`
