### ISSUE TITLE
1.0.5 is broken!

### ISSUE THREAD

**Issue by shiv19** [braune-digital/nativescript-share-file#8]
I think you forgot to run `npm run tsc` so 1.0.5 doesn't have the js files in it :/
Can you please re-publish?
@baltruschat

**Comment by acharyaks90** [comment]
Error: Can't resolve 'nativescript-share-file'

**Comment by acharyaks90** [comment]
@baltruschat Please publish again

**Comment by shiv19** [comment]
@acharyaks90 until the plugin is re-published you can switch back to version 1.0.4
