### ISSUE TITLE
TypeError: application.android.startActivity is not a function

### ISSUE THREAD

**Issue by adfdev** [braune-digital/nativescript-share-file#9]
I use nativescript 6
I have problem in android return me this error: 

`'ShareFile: Android intent failed'`

have individuate error in this part of code of share.file.android.ts file:

`try {
                var intent = new android.content.Intent();
                var map = android.webkit.MimeTypeMap.getSingleton();
                var mimeType = map.getMimeTypeFromExtension(this.fileExtension(args.path));
                intent.addFlags(android.content.Intent.FLAG_GRANT_READ_URI_PERMISSION);
                var uris = new java.util.ArrayList();
                var uri = this._getUriForPath(args.path, '/' + this.fileName(args.path), application.android.context);
                uris.add(uri);
                var builder = new android.os.StrictMode.VmPolicy.Builder();
                android.os.StrictMode.setVmPolicy(builder.build());
                intent.setAction(android.content.Intent.ACTION_SEND_MULTIPLE);
                intent.setType("message/rfc822");
                intent.putParcelableArrayListExtra(android.content.Intent.EXTRA_STREAM, uris);
                application.android.currentContext.startActivity(android.content.Intent.createChooser(intent, args.intentTitle ? args.intentTitle : 'Open file:'));
            }
            catch (e) {
                console.log(e) //add by me for debug
                console.log('ShareFile: Android intent failed');
            }`

`application.android.currentContext` result is undefined. How can resolve?

**Comment by alihimad** [comment]
@adfdev i have also got same problem, go to file:
node_modules\nativescript-share-file\share-file.android.js

and change following line 
    application.android.currentContext.startActivity(android.content.Intent.createChooser(intent, args.intentTitle ? args.intentTitle : 'Open file:'));
with
    application.android.context.startActivity(android.content.Intent.createChooser(intent, args.intentTitle ? args.intentTitle : 'Open file:'));

it will work

**Comment by adfdev** [comment]
have solved replaced currentContext with foregroundActivity
